# -*- coding: utf-8 -*-
"""Ecommerse_sales _Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18xh-W0LTuWf68uIXj4piUkrfnVsLwb8w
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("/content/ecommerce_sales_dirty.csv")

df.head()

df.tail()

df.shape

df.size

df.describe()

df.info()

df.isnull().sum()

df.duplicated().sum()

print(f"Rows before removing duplicates: {len(df)}")

df = df.drop_duplicates().reset_index(drop=True)

print(f"Rows after removing duplicates: {len(df)}")

print("-" * 40)

text_cols = df.select_dtypes(include=["object"]).columns

for col in text_cols:
    df[col] = df[col].astype(str).str.strip()

df[col] = df[col].replace({'nan': None, 'None': None, '': None})

if 'City' in df.columns:
    df['City'] = df['City'].str.title()

if 'Category' in df.columns:
    df['Category'] = df['Category'].str.title()

print(df.head())

# Convert mixed string formats into proper Datetime objects
df['Order_Date'] = pd.to_datetime(df['Order_Date'], format='mixed', errors='coerce')

df.head()

# For categorical features where context is missing, fill with 'Unknown'
categorical_nulls = ['Customer_Name', 'City', 'State', 'Region', 'Sub_Category', 'Product_Name']
for col in categorical_nulls:
    df[col] = df[col].fillna('Unknown')

df = df.dropna(subset=['Sales', 'Quantity', 'Discount', 'Profit']).reset_index(drop=True)

print(f"Remaining null values:\n{df.isnull().sum()}")

#Convert negative quantities and sales to positive absolute values
df['Quantity'] = df['Quantity'].abs()
df['Sales'] = df['Sales'].abs()

df['Discount'] = df['Discount'].apply(lambda x: 0.00 if x < 0 else (0.50 if x > 0.50 else x))

df['Quantity'] = df['Quantity'].astype(int)

df.to_csv("ecommerce_sales_cleaned.csv", index=False)

print("\nSuccess! Cleaned dataset saved as 'ecommerce_sales_cleaned.csv'")
print(f"Final Cleaned Shape: {df.shape}")

df.info()

